### ISSUE TITLE
the tool doesn't support the target_org parameter?

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/sf-warp#1]
From the help, it seems it doesn't support the usual `-o` to define which org to run against?
I was hesitated as it could run in any org in my `sf org list`.

Even with --verbosity details, the prompt in execution still doesn't tell the org.

**Comment by aheber** [comment]
I'll have to look at it. I think I always run it against the configured default org but didn't realize I didn't set it up to be able to configure the org. I'll have to make a change next week.

**Comment by aheber** [comment]
Existing flag was `--username` or `-o`, I've changed it to the updated standard of `--target-org` to match the other SF commands. `username` was left as a deprecated alias so any existing users wouldn't be broken.

Change is available in v0.0.14 and can be retrieved using `sf plugins update` or uninstalling and reinstalling sf-warp.
