### ISSUE TITLE
"Failure: This test is already in the execution queue."

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/sf-warp#2]
It seems when the tests take long to finish (in my case, due to maybe too many DMLs), the mutation tests carry on nonetheless and reached this.

```
Start Line 154 | string_literal
 -             body = body.replace('"id"', '"idX"');
 +             body = body.replace('"di"', '"idX"');
Failure: This test is already in the execution queue.
```

It'd be nice if it holds the horse or simply stop.

**Comment by aheber** [comment]
I'll have to see about fixing that. Most often that kind of behavior is because Salesforce didn't get around to starting the test run before we timed out.

I thought I had added logic to cancel the request but I'll look at it next week when I'm in front of a computer again.

**Comment by xixiaofinland** [comment]
No hurry at all. Just reporting the findings. Same as the other issue.

When I have small classes, well organized tests and minimal DMLs, this tool does a very good job. Details we can have a chat later in the future conversation :).

**Comment by aheber** [comment]
It'll take me a little longer to work on this. If it annoys you for now you can increase the timeout value with the `--timeout` parameter.

**Comment by xixiaofinland** [comment]
no problem at all. Take your time.

**Comment by aheber** [comment]
This should be much improved in v0.0.15. When an individual test times out then the plugin should correctly cancel that test execution, report a timeout failure, and move to the next test.
